### PR TITLE
Make the creation of security groups region aware

### PR DESCRIPTION
**Pull request by sxd**
Running the terraform apply we face the problem of having two regions when creating the security groups, this commit will make the creation region aware.

### CODE REVIEW

**Comment by Kiemes** [comment]
Hi @sxd, thanks for your pull request. Could you please sign the CLA as cfdreddbot described. Let us know when you did. We will merge afterwards.

**Comment by sxd** [comment]
Hi @Kiemes I just sent the CLA to contributors@cloudfoundry.org so you should already have it! =)

**Comment by sxd** [comment]
@Kiemes There's a way to know if they got my CLA? 

Regards!

**Comment by Kiemes** [comment]
I talked to the community colleagues today, but no response yet. Usually this is faster, that's why I wrote them. Will keep you updated here.

**Comment by sxd** [comment]
@Kiemes Chris Clark just confirmed by email that the CLA was filed and the permissions are updated =)

**Comment by Kiemes** [comment]
Thanks again @sxd. I just merged the PR

**Pull request merged**
